import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import StoreProvider from "@/components/ui/StoreProvider";
import Navbar from "@/components/ui/navbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <div className="fixed top-0 w-full z-50">
            <Navbar />
          </div>
          <div className="pt-[180px] lg:pt-[60px]"> {/* Padding-top 180px trên điện thoại, 60px trên màn hình lớn */}
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
